version: "3.7"

services:
  postgres:
    image: gangstead/postgis:13-3.1-arm
    container_name: pc-postgres
    volumes:
      - db_sync:/var/lib/postgresql/data:delegated
    env_file:
      - env_file
    networks:
      - db_nw
    ports:
      - 5434:5432
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on

  postgres-test:
    image: gangstead/postgis:13-3.1-arm
    container_name: pc-postgres-pytest
    volumes:
      - test_db_sync:/var/lib/postgresql-test/data:delegated
    environment:
      - POSTGRES_DB=pass_culture
      - POSTGRES_USER=pytest
      - POSTGRES_PASSWORD=pytest
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on
    ports:
      - 5433:5432
    networks:
      - db_nw

  flask:
    image: passcultureapp/api-flask:latest
    working_dir: /opt/services/flaskapp/src
    container_name: pc-flask
    command: ["./start-api-when-database-is-ready.sh"]
    volumes:
      - api_sync:/opt/services/flaskapp/src:delegated
    env_file:
      - env_file
      - ${ENV:-development}_env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres
      - redis
      - postgres-test
    ports:
      - 5000:5000
      - 10002:10002 # debugger port
    stdin_open: true
    tty: true

  redis:
    image: scalingo/redis
    container_name: pc-redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - db_nw

  nginx:
    build: nginx
    container_name: pc-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    networks:
      - web_nw
    depends_on:
      - flask

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  db_sync:
    external: true
  api_sync:
    external: true
  test_db_sync:
    external: true
  redis_data:
